### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [metanorma/metanorma-model-csa#1]
Convert metanorma CSAND StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse , please find the zip archives that include the results of conversion.
- [PNG.zip](https://github.com/riboseinc/metanorma-model-csand/files/2317207/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/metanorma-model-csand/files/2317208/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/metanorma-model-csand/files/2317209/SVG.zip)

**Comment by ronaldtse** [comment]
Done in f23a66bd900d5334f02a386aa25354a249490685. Thanks @VasBu !
